[package]
name = "dehydrated-s3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
enum_dispatch = "0.3.13"
http = "1.3.1"
tokio = { version = "1.44.2", features = ["full"] }
tokio-native-tls = "0.3.1"
